// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsknbtz3DFVv-W7LMYsH6YnOHL_NoyuQY',
    appId: '1:523096348418:web:7414df455a8d1dd35c541b',
    messagingSenderId: '523096348418',
    projectId: 'easychat-8ad9a',
    authDomain: 'easychat-8ad9a.firebaseapp.com',
    storageBucket: 'easychat-8ad9a.appspot.com',
    measurementId: 'G-N4LGMQBKTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw92Xz9vRMr-1wFNYhQ8bMhzTcUWyr5Ho',
    appId: '1:523096348418:android:4597c410196f31385c541b',
    messagingSenderId: '523096348418',
    projectId: 'easychat-8ad9a',
    storageBucket: 'easychat-8ad9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzTsVSkHYWRWFeAz1H44wdx_nP3Xabl7A',
    appId: '1:523096348418:ios:af7f8ca52e05fbbe5c541b',
    messagingSenderId: '523096348418',
    projectId: 'easychat-8ad9a',
    storageBucket: 'easychat-8ad9a.appspot.com',
    iosBundleId: 'dafinndus.de.messenger',
  );
}
